# -*- coding: utf-8 -*-
"""01_recsys_eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nc_Y9KpBJk5scgxBgRJktv_1dWgsNrcH
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install ydata_profiling

"""1. Import libraries
2. Load CSV files
3. Inspect tables
4. Create unified interactions table
5. Data quality checks
6. Clean invalid rows
7. Basic volume statistics
8. Sparsity and ALS readiness
9. User activity and cold-start
10. Discount popularity and long-tail
11. Interaction funnel and weights
12. Category, role, and location analysis
13. Time-based analysis
14. Model readiness summary
15. Data Quality Report for Wiki

#### 1&2 Import Libraries and Load Data
"""

import pandas as pd
import numpy as np
from pathlib import Path
import seaborn as sns
from ydata_profiling import ProfileReport
import matplotlib.pyplot as plt

path = Path("../data/raw/")

users_df = pd.read_csv(path / "users.csv")
categories_df = pd.read_csv(path / "categories_.csv")
category_discount_df = pd.read_csv( path / "category_discount_.csv")
countries_df = pd.read_csv(path / "countries_.csv")
discount_button_click_statistics_df = pd.read_csv(path / "discount_button_click_statistics_.csv")
discount_favourites_df = pd.read_csv(path / "discount_favourites_.csv")
discount_rates_df = pd.read_csv(path / "discount_rates_.csv")
discounts_df = pd.read_csv(path / "discounts.csv")
localization_default_df = pd.read_csv(path / "localization_default_.csv")
location_discount_df = pd.read_csv(path / "location_discount_.csv")
locations_df = pd.read_csv(path / "locations_.csv")
roles_df = pd.read_csv(path / "roles_.csv")
users_assigned_locations_df = pd.read_csv(path / "users_assigned_locations_.csv")

"""### Brief Introduction
users.csv → user information

discounts.csv → discount/item information

discount_button_click_statistics_.csv → click/show interaction events

discount_favourites_.csv → favourite events

discount_rates_.csv → like/dislike events

category_discount_.csv → discount-category relation

location_discount_.csv → discount-location relation

roles_.csv → role names

locations_.csv → location IDs
"""

tables = {
    "users": users_df,
    "categories": categories_df,
    "category_discount": category_discount_df,
    "countries": countries_df,
    "discount_button_click_statistics": discount_button_click_statistics_df,
    "discount_favourites": discount_favourites_df,
    "discount_rates": discount_rates_df,
    "discounts": discounts_df,
    "localization_default": localization_default_df,
    "location_discount": location_discount_df,
    "locations": locations_df,
    "roles": roles_df,
    "users_assigned_locations": users_assigned_locations_df
}

"""### 3.Inspect Tables"""

def dataset_overview(df, name):
    print(f"\n===== {name} =====")
    print("Shape:", df.shape)
    print("\nColumns:")
    print(df.columns.tolist())
    print("\nData types:")
    print(df.dtypes)
    print("\nFirst rows:")
    display(df.head())
    print("\nMissing values:")
    display(df.isna().sum().sort_values(ascending=False))
    print("\nDuplicates:", df.duplicated().sum())

for name,df in tables.items():
  dataset_overview(df,name)

summary_rows = []
for name,df in tables.items():
    summary_rows.append({
        'table_name':name,
        'n_rows':df.shape[0],
        'n_columns':df.shape[1],
        'duplicates':df.duplicated().sum(),
        'missing_total':df.isna().sum()
    })

tables_summary = pd.DataFrame(summary_rows)

tables_summary

for name,df in tables.items():
    print(f'Name:{name}')
    print(f'Column Names:{df.columns.tolist()}')

"""## 4. Create Unified Interactions Table

interactions = click_events + favourite_events  + rating_events
                            ////
user_id + item_id + interaction_type + time + weight

Each row represents one user action toward one discount item.

The table will be used to calculate interaction volume, sparsity, cold-start users/items, popularity bias, and ALS readiness.

The original data stores user actions in separate tables: button clicks, favourites, and ratings.

For recommender-system EDA, these actions are combined into one unified interaction table.
"""

click_events = discount_button_click_statistics_df.copy()

click_events.columns

click_events['name'].value_counts()
click_events['name']

click_events['statistics_type'].value_counts()
click_events['statistics_type']

click_events['event_type'] = click_events['name']
click_events['event_time'] = click_events['time_create']
click_events['source_table'] = "discount_button_click_statistics"

click_events['interaction_weight'] = click_events['event_type'].map({
    'SHOW_AT_LOCATION':0.1,
    'OPEN_CARD':0.3,
    'GET_A_PROMOCODE':2,
})

click_events["event_type"].value_counts()
click_events["interaction_weight"].isna().sum()
click_events.head()

click_events = click_events[['user_id','discount_id','event_type','event_time','interaction_weight','source_table','location_id','role_id']]

click_events["interaction_weight"].isna().sum()

favourite_events = discount_favourites_df.copy()

favourite_events['event_type'] = 'FAVOURITE'
favourite_events['event_time'] = favourite_events['created_at']
favourite_events['source_table'] = 'discount_favourites'
favourite_events['interaction_weight'] = 4.0

favourite_events['location_id'] = np.nan
favourite_events['role_id'] = np.nan

favourite_events = favourite_events[[
    'user_id',
    'discount_id',
    'event_type',
    'event_time',
    'interaction_weight',
    'source_table',
    'location_id',
    'role_id',
]]

favourite_events.head()

rating_events = discount_rates_df.copy()

rating_events['event_type'] = rating_events['rate_type']
rating_events['event_time'] = rating_events['created_at']
rating_events['source_table'] = 'discount_rates'

rating_events.head(3)

rating_events['rate_type'].value_counts()

rating_events['interaction_weight'] = rating_events['event_type'].map({
    'LIKE':3,
    'DISLIKE':-3
})

rating_events['location_id'] = np.nan
rating_events['role_id'] = np.nan

rating_events = rating_events[[
    'user_id',
    'discount_id',
    'event_type',
    'event_time',
    'interaction_weight',
    'source_table',
    'location_id',
    'role_id'
]]

dataset_overview(rating_events,'rating_events')

interactions_df = pd.concat(
    [click_events,favourite_events,rating_events],
    ignore_index=True
)

interactions_df.head()

interactions_df['source_table'].value_counts()

interactions_df['event_type'].value_counts()

interactions_df['interaction_weight'].isna().sum()

interactions_df.isna().sum()

"""The unified interactions table was successfully created by combining click, favourite, and rating events.
    The final table contains 35,336 interaction records and 6 event types.
    All interaction weights were assigned successfully, with no missing values.
    Missing role_id and location_id values are expected for favourite and rating events because these source tables do not contain contextual role or location information.

### 5. Data Quality Checks
"""

valid_user_ids = set(users_df['id'])
valid_discount_ids = set(discounts_df['id'])

missing_user_id = interactions_df['user_id'].isna().sum()
missing_discount_id = interactions_df['discount_id'].isna().sum()

invalid_user_mask = ~interactions_df['user_id'].isin(valid_user_ids)
invalid_discount_mask = ~interactions_df['discount_id'].isin(valid_discount_ids)

invalid_user_count = invalid_user_mask.sum()
invalid_discount_count = invalid_discount_mask.sum()

duplicated_interactions = interactions_df.duplicated().sum()
duplicated_interactions

data_quality_report = pd.DataFrame({
    'check':[
        "missing_user_id",
        "missing_discount_id",
        "invalid_user_id",
        "invalid_discount_id",
        'duplicate_rows'
    ],
    'count':[
        missing_user_id,
        missing_discount_id,
        invalid_user_count,
        invalid_discount_count,
        duplicated_interactions
    ]
})
data_quality_report

"""### 6. Clean Invalid Rows

Invalid interactions are removed before calculating recommender-system metrics.

An interaction is considered invalid if its user_id is not present in the users table or its discount_id is not present in the discounts table.
"""

valid_interaction_mask = (
    interactions_df['user_id'].isin(valid_user_ids)
    & interactions_df['discount_id'].isin(valid_discount_ids)
)

interactions_clean = interactions_df[valid_interaction_mask].copy()

interactions_clean.head(3)

removed_rows = len(interactions_df) - len(interactions_clean)
print('rows before cleaning:',len(interactions_df))
print('rows after cleaning:',len(interactions_clean))
print('Removed rows:',removed_rows)

print("Invalid users after cleaning:", (~interactions_clean["user_id"].isin(valid_user_ids)).sum())
print("Invalid discounts after cleaning:", (~interactions_clean["discount_id"].isin(valid_discount_ids)).sum())
print("Missing user_id:", interactions_clean["user_id"].isna().sum())
print("Missing discount_id:", interactions_clean["discount_id"].isna().sum())
print("Duplicate rows:", interactions_clean.duplicated().sum())

"""### 7. Basic Vol Statistics."""

n_users = users_df['id'].nunique()
n_discounts = discounts_df['id'].nunique()
n_interactions = len(interactions_clean)
n_unique_user_item_pairs = interactions_clean[['user_id','discount_id']].drop_duplicates().shape[0]

vol_stats = pd.DataFrame({
    'metric':[
        'unique_users',
        'unique_discounts',
        'total_interactions',
        'unique_user_item_pairs',
   ],
    'value':[
        n_users,
        n_discounts,
        n_interactions,
        n_unique_user_item_pairs
    ]
})

vol_stats

event_type_stats = (
    interactions_clean['event_type'].value_counts().reset_index()
)
event_type_stats.columns = ['event_type','count']
event_type_stats

event_type_stats['percentage'] = (
    event_type_stats['count']/event_type_stats['count'].sum()*100
).round(2)
event_type_stats

"""### 8. Sparsity and ALS Readiness"""

possible_item_pairs = n_users*n_discounts

density = n_unique_user_item_pairs / possible_item_pairs

sparsity = 1 - density

sparsity_stats = pd.DataFrame({
    'metric': ['possible_user_item_pairs',
     'observed_user_item_pairs',
     'density',
     'sparsity',
     'density_percent',
     'sparsity_percent',
     ],
    'value':[possible_item_pairs,n_unique_user_item_pairs,density,sparsity,density*100,sparsity*100]
    }
    )

sparsity_stats

"""ALS READINESS METRICS"""

user_interaction_counts = interactions_clean.groupby('user_id').size()
item_interaction_counts = interactions_clean.groupby('discount_id').size(

)

als_readiness_stats = pd.DataFrame({
    "metric": [
        "avg_interactions_per_active_user",
        "median_interactions_per_active_user",
        "avg_interactions_per_active_discount",
        "median_interactions_per_active_discount"
    ],
    "value": [
        user_interaction_counts.mean(),
        user_interaction_counts.median(),
        item_interaction_counts.mean(),
        item_interaction_counts.median()
    ]
})

als_readiness_stats

"""The interaction matrix is highly sparse, which means only a small fraction of all possible user-discount pairs were observed.

This suggests that pure ALS may not be enough for all users.

ALS can be useful for active users, but cold-start users need fallback recommendations based on popularity, category, role, or location.

### 9. User activity histogram
"""

user_activity = (
    interactions_clean
    .groupby("user_id")["discount_id"]
    .nunique()
    .reset_index()
)

user_activity.columns = ["user_id", "unique_discounts_interacted"]

user_activity.head()

all_users_activity = users_df[["id"]].copy()

all_users_activity = all_users_activity.merge(
    user_activity,
    left_on="id",
    right_on="user_id",
    how="left"
)

all_users_activity["unique_discounts_interacted"] = (
    all_users_activity["unique_discounts_interacted"].fillna(0)
)

all_users_activity.head()

total_users = len(all_users_activity)

zero_interaction_users = (all_users_activity["unique_discounts_interacted"] == 0).sum()
less_than_3_users = (all_users_activity["unique_discounts_interacted"] < 3).sum()
less_than_5_users = (all_users_activity["unique_discounts_interacted"] < 5).sum()

cold_start_stats = pd.DataFrame({
    "metric": [
        "total_users",
        "users_with_0_interactions",
        "users_with_less_than_3_interactions",
        "users_with_less_than_5_interactions",
        "share_0_interactions_percent",
        "share_less_than_3_percent",
        "share_less_than_5_percent"
    ],
    "value": [
        total_users,
        zero_interaction_users,
        less_than_3_users,
        less_than_5_users,
        zero_interaction_users / total_users * 100,
        less_than_3_users / total_users * 100,
        less_than_5_users / total_users * 100
    ]
})

cold_start_stats

plt.figure(figsize=(10, 5))

plt.hist(
    all_users_activity["unique_discounts_interacted"],
    bins=30
)

plt.title("User Activity Distribution")
plt.xlabel("Number of Unique Discounts Interacted")
plt.ylabel("Number of Users")
plt.show()

plt.figure(figsize=(10, 5))

plt.hist(
    all_users_activity["unique_discounts_interacted"].clip(upper=30),
    bins=30
)

plt.title("User Activity Distribution, Clipped")
plt.xlabel("Number of Unique Discounts Interacted")
plt.ylabel("Number of Users")
plt.show()

user_roles = users_df[["id", "role_id"]].copy()

user_roles = user_roles.rename(columns={
    "id": "user_id",
    "role_id": "user_role_id"
})

user_roles

role_names = roles_df[["id", "name"]].copy()

role_names = role_names.rename(columns={
    "id": "user_role_id",
    "name": "role_name"
})
role_names

discount_categories = category_discount_df[['discount_id','category_id']].copy()
discount_categories.head()

category_names = categories_df[['id','title']].copy()

category_names = category_names.rename(columns={
    'id':'category_id',
    'title':'category_name'
})
category_names.head()

interactions_with_context = interactions_clean.merge(user_roles,on='user_id',how='left')
interactions_with_context = interactions_with_context.merge(role_names,on='user_role_id',how='left')
interactions_with_context = interactions_with_context.merge(discount_categories,on='discount_id',how='left')
interactions_with_context = interactions_with_context.merge(category_names,on='category_id',how='left')
interactions_with_context.head()

interactions_with_context[['role_name','category_name']].isna().sum()

role_category_matrix = pd.pivot_table(
    interactions_with_context,
    index='role_name',
    columns='category_name',
    values='user_id',
    aggfunc='count',
    fill_value=0

)
role_category_matrix

plt.figure(figsize=(10,6))
sns.heatmap(role_category_matrix,
            annot=True,
            fmt='.0f',
            cmap='Blues')

plt.title('Role & Category Interaction Heatmap')
plt.xlabel('Category')
plt.ylabel('Role Name')
plt.xticks(rotation=45,ha='right')
plt.show()

"""### Heatmap Correlation"""

discount_event_features = (
    interactions_clean.pivot_table(
        index='discount_id',
        columns='event_type',
        values='user_id',
        aggfunc='count',
        fill_value=0
    ).reset_index())

discount_event_features.head()

discount_scores = (
    interactions_clean
    .groupby("discount_id")
    .agg(
        total_interactions=("user_id", "size"),
        weighted_score=("interaction_weight", "sum"),
        unique_users=("user_id", "nunique")
    )
    .reset_index()
)

discount_scores.head()

discount_corr_features = discount_event_features.merge(
    discount_scores,
    on="discount_id",
    how="left"
)

discount_corr_features.head()

corr_input = discount_corr_features.drop(columns=["discount_id"])

corr_matrix = corr_input.corr()

corr_matrix

plt.figure(figsize=(10,6))
sns.heatmap(corr_matrix,
            annot=True,
            fmt='.2f',
            cmap='coolwarm',
            center=0)
plt.title('Correlation Heatmap')
plt.show()